# black:
#   max:
#   - 70
#   - 70
#   - 70
#   min:
#   - 0
#   - 0
#   - 0
# blue:
#   max:
#   - 255
#   - 100
#   - 100
#   min:
#   - 150
#   - 0
#   - 0
# green:
#   max:
#   - 100
#   - 255
#   - 100
#   min:
#   - 0
#   - 150
#   - 0
# red:
#   max:
#   - 140
#   - 140
#   - 255
#   min:
#   - 0
#   - 0
#   - 210
# white:
#   max:
#   - 255
#   - 255
#   - 255
#   min:
#   - 200
#   - 200
#   - 200
black:
  max:
  - 115
  - 135
  - 115
  min:
  - 0
  - 0
  - 0
blue:
  max:
  - 255
  - 255
  - 160
  min:
  - 120
  - 0
  - 0
green:
  max:
  - 100
  - 255
  - 100
  min:
  - 0
  - 100
  - 0
red:
  max:
  - 120
  - 110
  - 255
  min:
  - 20
  - 0
  - 210
white:
  max:
  - 255
  - 255
  - 255
  min:
  - 193
  - 0
  - 0
lightblue:
  max:
  - 160
  - 160
  - 150
  min:
  - 95
  - 110
  - 110